concourse_url: http://concourse.example.com
concourse_team: main
concourse_username:
concourse_password:

booking_agent_uri: https://github.com/RMeharg/booking-agent
booking_agent_username:
booking_agent_password:

pipelines_uri: https://gitlab.com/ORG/REPO
pipelines_username:
pipelines_password:

environments_uri: https://gitlab.com/ORG/REPO
environments_username:
environments_password:
